import type { IActivity } from "@/lib/strava/types";

/** Builds a minimally-valid IActivity for tests, with just the fields that matter overridden. */
export const makeActivity = (overrides: Partial<IActivity> = {}): IActivity => ({
  id: 1,
  external_id: "1",
  resource_state: "2",
  athlete: { id: 1, resource_state: 1 },
  name: "Test activity",
  distance: 0,
  moving_time: 0,
  elapsed_time: 0,
  total_elevation_gain: 0,
  type: "Run",
  workout_type: "",
  start_date: "2024-01-01T00:00:00Z",
  start_date_local: "2024-01-01T00:00:00Z",
  timezone: "",
  utc_offset: 0,
  start_latlng: "",
  end_latlng: "",
  location_city: "",
  location_state: "",
  location_country: "",
  achievement_count: 0,
  kudos_count: 0,
  comment_count: 0,
  athlete_count: 0,
  photo_count: 0,
  map: { id: "", summery_polyline: "", resource_state: 0 },
  trainer: false,
  commute: false,
  manual: false,
  private: false,
  flagged: false,
  gear_id: "",
  from_accepted_tag: false,
  average_speed: 0,
  max_speed: 0,
  average_cadence: 0,
  average_watts: 0,
  weighted_average_watts: 0,
  kilojoules: 0,
  device_watts: false,
  has_heartrate: false,
  average_heartrate: 0,
  max_heartrate: 0,
  max_watts: 0,
  pr_count: 0,
  total_photo_count: 0,
  has_kudoed: false,
  suffer_score: 0,
  ...overrides,
});
