name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Install dependencies for functions
        working-directory: ./functions
        run: npm install

      - name: Build SPA
        run: npm run build

      - name: Deploy application
        run: firebase deploy
